#!/usr/bin/bash

function usage() {
    cat <<EOF
Usage: $0 <ip> <port> <folder>
EOF
}

function scan() {
    mkdir -p $3
    sudo nmap $1 -p $2 -sV --script vuln -oA $3/$1_vuln_$2
}

if [[ -z $1 || -z $2 || -z $3 ]]; then
    usage
    exit 1
fi

scan $1 $2 $3
